package com.oracle.model.common;

import java.util.List;
import java.util.Map;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 13 19:05:17 IST 2025
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    Map<String, Object> buildDynamicSQL(String actionType, String filterAttributes, String filterValues,
                                        String filterOperations, String displayColumns);

    Map<String, Object> executeDynamicQuery(String sqlQuery, String[] paramValues, String[] paramTypes);

    Map<String, Object> executeNLPQuery(String actionType, String filterAttributes, String filterValues,
                                        String filterOperations, String displayColumns);

    Map pullContractDatesByAwardNumber(String awardNumber);

    Map pullContractsByFilters(String userName, List dateFilters, String query);

    Map<String, Object> pullCustomerDetails(String customerNumber);

    Map<String, Object> createContractByBOT(Map<String, Object> contractData, String createdBy);
}

